# Language flags.
language: rust

# OS matrix.
os:
  - linux
  - osx
  - windows

# Services listing.
services:
  - docker

# Version matrix.
rust:
  - stable
  - beta
  - nightly

# Cargo caching.
cache:
  cargo: true

# Custom scripts.
script:
  - cargo build --verbose --all --all-features
  - cargo test --verbose --all --all-features

# Matrix modifications.
matrix:

  # Failures to allow.
  allow_failures:
    - rust: nightly

  # Additional builds.
  include:

    # Clippy linting.
    - rust: stable
      os: linux
      script:
        - rustup component add clippy
        - cargo clippy --all --all-features --profile test

    # Format linting.
    - rust: stable
      os: linux
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check
